/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOnObject {
    /// Unique identifier of the add-on, created by Lago.
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// The name of the add-on.
    #[serde(rename = "name")]
    pub name: String,
    /// Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the actual charge will be used as the default display name.
    #[serde(rename = "invoice_display_name", skip_serializing_if = "Option::is_none")]
    pub invoice_display_name: Option<String>,
    /// Unique code used to identify the add-on.
    #[serde(rename = "code")]
    pub code: String,
    /// The cost of the add-on in cents, excluding any applicable taxes, that is billed to a customer. By creating a one-off invoice, you will be able to override this value.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    /// The currency of the add-on.
    #[serde(rename = "amount_currency")]
    pub amount_currency: models::Currency,
    /// The description of the add-on.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The date and time when the add-on was created. It is expressed in UTC format according to the ISO 8601 datetime standard. This field provides the timestamp for the exact moment when the add-on was initially created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// All taxes applied to the add-on.
    #[serde(rename = "taxes", skip_serializing_if = "Option::is_none")]
    pub taxes: Option<Vec<models::TaxObject>>,
}

impl AddOnObject {
    pub fn new(lago_id: uuid::Uuid, name: String, code: String, amount_cents: i32, amount_currency: models::Currency, created_at: String) -> AddOnObject {
        AddOnObject {
            lago_id,
            name,
            invoice_display_name: None,
            code,
            amount_cents,
            amount_currency,
            description: None,
            created_at,
            taxes: None,
        }
    }
}

