/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppliedCouponsPaginated {
    #[serde(rename = "applied_coupons")]
    pub applied_coupons: Vec<models::AppliedCouponObjectExtended>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl AppliedCouponsPaginated {
    pub fn new(applied_coupons: Vec<models::AppliedCouponObjectExtended>, meta: models::PaginationMeta) -> AppliedCouponsPaginated {
        AppliedCouponsPaginated {
            applied_coupons,
            meta: Box::new(meta),
        }
    }
}

