/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillableMetricEvaluateExpressionInput {
    /// Expression used to calculate the event units. The expression is evalutated for each event and the result is then used to calculate the total aggregated units. Accepted function are `ceil`, `concat` and `round` as well as `+`, `-`, `\\` and `*` operations. Round is accepting an optional second parameter to specify the number of decimal. 
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "event")]
    pub event: Box<models::BillableMetricEvaluateExpressionInputEvent>,
}

impl BillableMetricEvaluateExpressionInput {
    pub fn new(expression: String, event: models::BillableMetricEvaluateExpressionInputEvent) -> BillableMetricEvaluateExpressionInput {
        BillableMetricEvaluateExpressionInput {
            expression,
            event: Box::new(event),
        }
    }
}

