/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillableMetricsPaginated {
    #[serde(rename = "billable_metrics")]
    pub billable_metrics: Vec<models::BillableMetricObject>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl BillableMetricsPaginated {
    pub fn new(billable_metrics: Vec<models::BillableMetricObject>, meta: models::PaginationMeta) -> BillableMetricsPaginated {
        BillableMetricsPaginated {
            billable_metrics,
            meta: Box::new(meta),
        }
    }
}

