/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillableMetricEvaluateExpressionInputEvent {
    /// The code that identifies a targeted billable metric.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Box<models::BillableMetricEvaluateExpressionInputEventTimestamp>>,
    /// This field represents additional properties associated with the event. They can be used when evaluating the expression.
    #[serde(rename = "properties")]
    pub properties: std::collections::HashMap<String, models::BillableMetricEvaluateExpressionInputEventPropertiesValue>,
}

impl BillableMetricEvaluateExpressionInputEvent {
    pub fn new(code: String, properties: std::collections::HashMap<String, models::BillableMetricEvaluateExpressionInputEventPropertiesValue>) -> BillableMetricEvaluateExpressionInputEvent {
        BillableMetricEvaluateExpressionInputEvent {
            code,
            timestamp: None,
            properties,
        }
    }
}

