/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BillableMetricEvaluateExpressionInputEventPropertiesValue {
    String(String),
    Integer(i32),
    Number(f64),
}

impl Default for BillableMetricEvaluateExpressionInputEventPropertiesValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

