/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChargeObject {
    /// Unique identifier of charge, created by Lago.
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// Unique identifier of the billable metric created by Lago.
    #[serde(rename = "lago_billable_metric_id")]
    pub lago_billable_metric_id: uuid::Uuid,
    /// Unique code identifying a billable metric.
    #[serde(rename = "billable_metric_code")]
    pub billable_metric_code: String,
    /// Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the actual charge will be used as the default display name.
    #[serde(rename = "invoice_display_name", skip_serializing_if = "Option::is_none")]
    pub invoice_display_name: Option<String>,
    /// The date and time when the charge was created. It is expressed in UTC format according to the ISO 8601 datetime standard.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Specifies the pricing model used for the calculation of the final fee. It can be `standard`, `graduated`, `graduated_percentage`, `package`, `percentage`, `volume` or `dynamic`.
    #[serde(rename = "charge_model")]
    pub charge_model: ChargeModel,
    /// This field determines the billing timing for this specific usage-based charge. When set to `true`, the charge is due and invoiced immediately. Conversely, when set to `false`, the charge is due and invoiced at the end of each billing period.
    #[serde(rename = "pay_in_advance", skip_serializing_if = "Option::is_none")]
    pub pay_in_advance: Option<bool>,
    /// This field specifies whether the charge should be included in a proper invoice. If set to `false`, no invoice will be issued for this charge. You can only set it to `false` when `pay_in_advance` is `true`.
    #[serde(rename = "invoiceable", skip_serializing_if = "Option::is_none")]
    pub invoiceable: Option<bool>,
    /// This setting can only be configured if `pay_in_advance` is `true` and `invoiceable` is `false`. This field determines whether and when the charge fee should be included in the invoice. If `null`, no invoice will be issued for this charge fee. If `invoice`, an invoice will be generated at the end of the period, consolidating all charge fees with a succeeded payment status.
    #[serde(rename = "regroup_paid_fees", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub regroup_paid_fees: Option<Option<RegroupPaidFees>>,
    /// Specifies whether a charge is prorated based on the remaining number of days in the billing period or billed fully.  - If set to `true`, the charge is prorated based on the remaining days in the current billing period. - If set to `false`, the charge is billed in full. - If not defined in the request, default value is `false`.
    #[serde(rename = "prorated", skip_serializing_if = "Option::is_none")]
    pub prorated: Option<bool>,
    /// The minimum spending amount required for the charge, measured in cents and excluding any applicable taxes. It indicates the minimum amount that needs to be charged for each billing period.
    #[serde(rename = "min_amount_cents", skip_serializing_if = "Option::is_none")]
    pub min_amount_cents: Option<i32>,
    /// List of all thresholds utilized for calculating the charge.
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::ChargeProperties>>,
    /// List of filters used to apply differentiated pricing based on additional event properties.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::ChargeFilterObject>>,
    /// All taxes applied to the charge.
    #[serde(rename = "taxes", skip_serializing_if = "Option::is_none")]
    pub taxes: Option<Vec<models::TaxObject>>,
}

impl ChargeObject {
    pub fn new(lago_id: uuid::Uuid, lago_billable_metric_id: uuid::Uuid, billable_metric_code: String, created_at: String, charge_model: ChargeModel) -> ChargeObject {
        ChargeObject {
            lago_id,
            lago_billable_metric_id,
            billable_metric_code,
            invoice_display_name: None,
            created_at,
            charge_model,
            pay_in_advance: None,
            invoiceable: None,
            regroup_paid_fees: None,
            prorated: None,
            min_amount_cents: None,
            properties: None,
            filters: None,
            taxes: None,
        }
    }
}
/// Specifies the pricing model used for the calculation of the final fee. It can be `standard`, `graduated`, `graduated_percentage`, `package`, `percentage`, `volume` or `dynamic`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChargeModel {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "graduated")]
    Graduated,
    #[serde(rename = "graduated_percentage")]
    GraduatedPercentage,
    #[serde(rename = "package")]
    Package,
    #[serde(rename = "percentage")]
    Percentage,
    #[serde(rename = "volume")]
    Volume,
    #[serde(rename = "dynamic")]
    Dynamic,
}

impl Default for ChargeModel {
    fn default() -> ChargeModel {
        Self::Standard
    }
}
/// This setting can only be configured if `pay_in_advance` is `true` and `invoiceable` is `false`. This field determines whether and when the charge fee should be included in the invoice. If `null`, no invoice will be issued for this charge fee. If `invoice`, an invoice will be generated at the end of the period, consolidating all charge fees with a succeeded payment status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegroupPaidFees {
    #[serde(rename = "invoice")]
    Invoice,
}

impl Default for RegroupPaidFees {
    fn default() -> RegroupPaidFees {
        Self::Invoice
    }
}

