/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CouponBaseInputAppliesTo : Set coupon limitations to plans or specific metrics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponBaseInputAppliesTo {
    /// An array of plan codes to which the coupon is applicable. By specifying the plan codes in this field, you can restrict the coupon's usage to specific plans only.
    #[serde(rename = "plan_codes", skip_serializing_if = "Option::is_none")]
    pub plan_codes: Option<Vec<String>>,
    /// An array of billable metric codes to which the coupon is applicable. By specifying the billable metric codes in this field, you can restrict the coupon's usage to specific metrics only.
    #[serde(rename = "billable_metric_codes", skip_serializing_if = "Option::is_none")]
    pub billable_metric_codes: Option<Vec<String>>,
}

impl CouponBaseInputAppliesTo {
    /// Set coupon limitations to plans or specific metrics.
    pub fn new() -> CouponBaseInputAppliesTo {
        CouponBaseInputAppliesTo {
            plan_codes: None,
            billable_metric_codes: None,
        }
    }
}

