/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponsPaginated {
    #[serde(rename = "coupons")]
    pub coupons: Vec<models::CouponObject>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl CouponsPaginated {
    pub fn new(coupons: Vec<models::CouponObject>, meta: models::PaginationMeta) -> CouponsPaginated {
        CouponsPaginated {
            coupons,
            meta: Box::new(meta),
        }
    }
}

