/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePaymentRequestRequestPaymentRequest {
    /// The customer external unique identifier (provided by your own application)
    #[serde(rename = "customer_external_id", skip_serializing_if = "Option::is_none")]
    pub customer_external_id: Option<String>,
    /// The customer's email address used for sending dunning notifications
    #[serde(rename = "email")]
    pub email: String,
    /// A list of Lago IDs for the customer's overdue invoices to start the dunning process
    #[serde(rename = "lago_invoice_ids")]
    pub lago_invoice_ids: Vec<String>,
}

impl CreatePaymentRequestRequestPaymentRequest {
    pub fn new(email: String, lago_invoice_ids: Vec<String>) -> CreatePaymentRequestRequestPaymentRequest {
        CreatePaymentRequestRequestPaymentRequest {
            customer_external_id: None,
            email,
            lago_invoice_ids,
        }
    }
}

