/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePaymentRequest200Response {
    #[serde(rename = "payment_request")]
    pub payment_request: Box<models::PaymentRequestObject>,
}

impl CreatePaymentRequest200Response {
    pub fn new(payment_request: models::PaymentRequestObject) -> CreatePaymentRequest200Response {
        CreatePaymentRequest200Response {
            payment_request: Box::new(payment_request),
        }
    }
}

