/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditNoteEstimateInputCreditNoteItemsInner {
    /// The fee unique identifier, created by Lago.
    #[serde(rename = "fee_id")]
    pub fee_id: uuid::Uuid,
    /// The amount of the credit note item, expressed in cents.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
}

impl CreditNoteEstimateInputCreditNoteItemsInner {
    pub fn new(fee_id: uuid::Uuid, amount_cents: i32) -> CreditNoteEstimateInputCreditNoteItemsInner {
        CreditNoteEstimateInputCreditNoteItemsInner {
            fee_id,
            amount_cents,
        }
    }
}

