/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditObject {
    /// Unique identifier assigned to the credit within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the credit's item record within the Lago system.
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// The amount of credit associated with the invoice, expressed in cents.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    /// The currency of the credit.
    #[serde(rename = "amount_currency")]
    pub amount_currency: models::Currency,
    /// Indicates whether the credit is applied on the amount before taxes (coupons) or after taxes (credit notes). This flag helps determine the order in which credits are applied to the invoice calculation
    #[serde(rename = "before_taxes")]
    pub before_taxes: bool,
    #[serde(rename = "item")]
    pub item: Box<models::CreditObjectItem>,
    #[serde(rename = "invoice")]
    pub invoice: Box<models::CreditObjectInvoice>,
}

impl CreditObject {
    pub fn new(lago_id: uuid::Uuid, amount_cents: i32, amount_currency: models::Currency, before_taxes: bool, item: models::CreditObjectItem, invoice: models::CreditObjectInvoice) -> CreditObject {
        CreditObject {
            lago_id,
            amount_cents,
            amount_currency,
            before_taxes,
            item: Box::new(item),
            invoice: Box::new(invoice),
        }
    }
}

