/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditNoteItemObject {
    /// The credit note's item unique identifier, created by Lago.
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// The credit note's item amount, expressed in cents.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    /// The credit note's item currency.
    #[serde(rename = "amount_currency")]
    pub amount_currency: models::Currency,
    /// The fee object related to the credit note item.
    #[serde(rename = "fee")]
    pub fee: Box<models::FeeObject>,
}

impl CreditNoteItemObject {
    pub fn new(lago_id: uuid::Uuid, amount_cents: i32, amount_currency: models::Currency, fee: models::FeeObject) -> CreditNoteItemObject {
        CreditNoteItemObject {
            lago_id,
            amount_cents,
            amount_currency,
            fee: Box::new(fee),
        }
    }
}

