/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomersPaginated {
    #[serde(rename = "customers")]
    pub customers: Vec<models::CustomerObjectExtended>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl CustomersPaginated {
    pub fn new(customers: Vec<models::CustomerObjectExtended>, meta: models::PaginationMeta) -> CustomersPaginated {
        CustomersPaginated {
            customers,
            meta: Box::new(meta),
        }
    }
}

