/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCreateInputCustomerMetadataInner {
    /// Identifier for the metadata object, only required when updating a key-value pair
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The metadata object key
    #[serde(rename = "key")]
    pub key: String,
    /// The metadata object value
    #[serde(rename = "value")]
    pub value: String,
    /// Determines whether the item or information should be displayed in the invoice. If set to true, the item or information will be included and visible in the generated invoice. If set to false, the item or information will be excluded and not displayed in the invoice.
    #[serde(rename = "display_in_invoice")]
    pub display_in_invoice: bool,
}

impl CustomerCreateInputCustomerMetadataInner {
    pub fn new(key: String, value: String, display_in_invoice: bool) -> CustomerCreateInputCustomerMetadataInner {
        CustomerCreateInputCustomerMetadataInner {
            id: None,
            key,
            value,
            display_in_invoice,
        }
    }
}

