/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerChargeUsageObjectCharge : Object listing all the properties for a specific charge item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerChargeUsageObjectCharge {
    /// Unique identifier assigned to the charge within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the charge's record within the Lago system.
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// The pricing model applied to this charge. Possible values are standard, `graduated`, `percentage`, `package` or `volume`.
    #[serde(rename = "charge_model")]
    pub charge_model: ChargeModel,
    /// Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the actual charge will be used as the default display name.
    #[serde(rename = "invoice_display_name", skip_serializing_if = "Option::is_none")]
    pub invoice_display_name: Option<String>,
}

impl CustomerChargeUsageObjectCharge {
    /// Object listing all the properties for a specific charge item.
    pub fn new(lago_id: uuid::Uuid, charge_model: ChargeModel) -> CustomerChargeUsageObjectCharge {
        CustomerChargeUsageObjectCharge {
            lago_id,
            charge_model,
            invoice_display_name: None,
        }
    }
}
/// The pricing model applied to this charge. Possible values are standard, `graduated`, `percentage`, `package` or `volume`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChargeModel {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "graduated")]
    Graduated,
    #[serde(rename = "package")]
    Package,
    #[serde(rename = "percentage")]
    Percentage,
    #[serde(rename = "volume")]
    Volume,
}

impl Default for ChargeModel {
    fn default() -> ChargeModel {
        Self::Standard
    }
}

