/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerMetadata : Set of key-value pairs that you can attach to a customer. This can be useful for storing additional information about the customer in a structured format
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerMetadata {
    /// A unique identifier for the customer metadata object in the Lago application. Can be used to update a key-value pair
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// The metadata object key
    #[serde(rename = "key")]
    pub key: String,
    /// The metadata object value
    #[serde(rename = "value")]
    pub value: String,
    /// Determines whether the item or information should be displayed in the invoice. If set to true, the item or information will be included and visible in the generated invoice. If set to false, the item or information will be excluded and not displayed in the invoice.
    #[serde(rename = "display_in_invoice")]
    pub display_in_invoice: bool,
    /// The date of the metadata object creation, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC). The creation_date provides a standardized and internationally recognized timestamp for when the metadata object was created
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl CustomerMetadata {
    /// Set of key-value pairs that you can attach to a customer. This can be useful for storing additional information about the customer in a structured format
    pub fn new(lago_id: uuid::Uuid, key: String, value: String, display_in_invoice: bool, created_at: String) -> CustomerMetadata {
        CustomerMetadata {
            lago_id,
            key,
            value,
            display_in_invoice,
            created_at,
        }
    }
}

