/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerUsage {
    #[serde(rename = "customer_usage")]
    pub customer_usage: Box<models::CustomerUsageObject>,
}

impl CustomerUsage {
    pub fn new(customer_usage: models::CustomerUsageObject) -> CustomerUsage {
        CustomerUsage {
            customer_usage: Box::new(customer_usage),
        }
    }
}

