/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerChargeFiltersUsageObjectInner {
    /// The number of units consumed for a specific charge filter related to a charge item.
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    /// The amount in cents, tax excluded, consumed for a specific charge filter related to a charge item.
    #[serde(rename = "amount_cents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    /// The quantity of usage events that have been recorded for a particular charge filter during the specified time period. These events may also be referred to as the number of transactions in some contexts.
    #[serde(rename = "events_count", skip_serializing_if = "Option::is_none")]
    pub events_count: Option<i32>,
    /// Specifies the name that will be displayed on an invoice.
    #[serde(rename = "invoice_display_name", skip_serializing_if = "Option::is_none")]
    pub invoice_display_name: Option<String>,
    /// List of filter values applied to the usage.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
}

impl CustomerChargeFiltersUsageObjectInner {
    pub fn new() -> CustomerChargeFiltersUsageObjectInner {
        CustomerChargeFiltersUsageObjectInner {
            units: None,
            amount_cents: None,
            events_count: None,
            invoice_display_name: None,
            values: None,
        }
    }
}

