/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventObject {
    /// Unique identifier assigned to the event within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the event's record within the Lago system
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    /// This field represents a unique identifier for the event. It is crucial for ensuring idempotency, meaning that each event can be uniquely identified and processed without causing any unintended side effects.
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    /// Unique identifier assigned to the customer within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the customer's record within the Lago system
    #[serde(rename = "lago_customer_id")]
    pub lago_customer_id: uuid::Uuid,
    /// The code that identifies a targeted billable metric. It is essential that this code matches the `code` property of one of your active billable metrics. If the provided code does not correspond to any active billable metric, it will be ignored during the process.
    #[serde(rename = "code")]
    pub code: String,
    /// This field captures the Unix timestamp in seconds indicating the occurrence of the event in Coordinated Universal Time (UTC). If this timestamp is not provided, the API will automatically set it to the time of event reception.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// The precise total amount that was sent in the event payload. This filed is used by the `dynamic` pricing model.
    #[serde(rename = "precise_total_amount_cents", skip_serializing_if = "Option::is_none")]
    pub precise_total_amount_cents: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<models::EventObjectProperties>,
    /// Unique identifier assigned to the subscription within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the subscription's record within the Lago system
    #[serde(rename = "lago_subscription_id")]
    pub lago_subscription_id: uuid::Uuid,
    /// The unique identifier of the subscription within your application. It is a mandatory field when the customer possesses multiple subscriptions or when the `external_customer_id` is not provided.
    #[serde(rename = "external_subscription_id")]
    pub external_subscription_id: String,
    /// The creation date of the event's record in the Lago application, presented in the ISO 8601 datetime format, specifically in Coordinated Universal Time (UTC). It provides the precise timestamp of when the event's record was created within the Lago application
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl EventObject {
    pub fn new(lago_id: uuid::Uuid, transaction_id: String, lago_customer_id: uuid::Uuid, code: String, timestamp: String, lago_subscription_id: uuid::Uuid, external_subscription_id: String, created_at: String) -> EventObject {
        EventObject {
            lago_id,
            transaction_id,
            lago_customer_id,
            code,
            timestamp,
            precise_total_amount_cents: None,
            properties: None,
            lago_subscription_id,
            external_subscription_id,
            created_at,
        }
    }
}

