/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeObjectAmountDetailsGraduatedRangesInner {
    /// Total units received in Lago.
    #[serde(rename = "units")]
    pub units: String,
    /// Lower value of a tier. It is either 0 or the previous range's `to_value + 1`.
    #[serde(rename = "from_value")]
    pub from_value: i32,
    /// Highest value of a tier. - This value is higher than the from_value of the same tier. - This value is null for the last tier.
    #[serde(rename = "to_value")]
    pub to_value: i32,
    /// Flat unit amount within a specified tier.
    #[serde(rename = "flat_unit_amount")]
    pub flat_unit_amount: String,
    /// Amount per unit within a specified tier.
    #[serde(rename = "per_unit_amount")]
    pub per_unit_amount: String,
    /// Total amount of received units to be charged within a specified tier.
    #[serde(rename = "per_unit_total_amount")]
    pub per_unit_total_amount: String,
    /// Total amount to be charged for a specific tier, taking into account the flat_unit_amount and the per_unit_total_amount.
    #[serde(rename = "total_with_flat_amount")]
    pub total_with_flat_amount: String,
}

impl FeeObjectAmountDetailsGraduatedRangesInner {
    pub fn new(units: String, from_value: i32, to_value: i32, flat_unit_amount: String, per_unit_amount: String, per_unit_total_amount: String, total_with_flat_amount: String) -> FeeObjectAmountDetailsGraduatedRangesInner {
        FeeObjectAmountDetailsGraduatedRangesInner {
            units,
            from_value,
            to_value,
            flat_unit_amount,
            per_unit_amount,
            per_unit_total_amount,
            total_with_flat_amount,
        }
    }
}

