/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenerateCustomerCheckoutUrl200Response : .
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateCustomerCheckoutUrl200Response {
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<Box<models::GenerateCustomerCheckoutUrl200ResponseCustomer>>,
}

impl GenerateCustomerCheckoutUrl200Response {
    /// .
    pub fn new() -> GenerateCustomerCheckoutUrl200Response {
        GenerateCustomerCheckoutUrl200Response {
            customer: None,
        }
    }
}

