/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrossRevenues {
    #[serde(rename = "gross_revenues")]
    pub gross_revenues: Vec<models::GrossRevenueObject>,
}

impl GrossRevenues {
    pub fn new(gross_revenues: Vec<models::GrossRevenueObject>) -> GrossRevenues {
        GrossRevenues {
            gross_revenues,
        }
    }
}

