/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoicedUsages {
    #[serde(rename = "invoiced_usages")]
    pub invoiced_usages: Vec<models::InvoicedUsageObject>,
}

impl InvoicedUsages {
    pub fn new(invoiced_usages: Vec<models::InvoicedUsageObject>) -> InvoicedUsages {
        InvoicedUsages {
            invoiced_usages,
        }
    }
}

