/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceUpdateInputInvoiceMetadataInner {
    /// The metadata object identifier. Only required when updating existing metadata.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The key in the key-value pair of the metadata.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The value in the key-value pair of the metadata.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl InvoiceUpdateInputInvoiceMetadataInner {
    pub fn new() -> InvoiceUpdateInputInvoiceMetadataInner {
        InvoiceUpdateInputInvoiceMetadataInner {
            id: None,
            key: None,
            value: None,
        }
    }
}

