/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoicePaymentUrl200Response : .
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoicePaymentUrl200Response {
    #[serde(rename = "invoice_payment_details", skip_serializing_if = "Option::is_none")]
    pub invoice_payment_details: Option<Box<models::InvoicePaymentUrl200ResponseInvoicePaymentDetails>>,
}

impl InvoicePaymentUrl200Response {
    /// .
    pub fn new() -> InvoicePaymentUrl200Response {
        InvoicePaymentUrl200Response {
            invoice_payment_details: None,
        }
    }
}

