/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceCollections {
    #[serde(rename = "invoice_collections")]
    pub invoice_collections: Vec<models::InvoiceCollectionObject>,
}

impl InvoiceCollections {
    pub fn new(invoice_collections: Vec<models::InvoiceCollectionObject>) -> InvoiceCollections {
        InvoiceCollections {
            invoice_collections,
        }
    }
}

