/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifetimeUsageInputLifetimeUsage {
    /// The historical usage amount in cents for the subscription (provided by your own application).
    #[serde(rename = "external_historical_usage_amount_cents")]
    pub external_historical_usage_amount_cents: i32,
}

impl LifetimeUsageInputLifetimeUsage {
    pub fn new(external_historical_usage_amount_cents: i32) -> LifetimeUsageInputLifetimeUsage {
        LifetimeUsageInputLifetimeUsage {
            external_historical_usage_amount_cents,
        }
    }
}

