/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifetimeUsageThresholdObject {
    /// The usage threshold amount in cents.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    /// The completion ratio of the usage threshold.
    #[serde(rename = "completion_ratio")]
    pub completion_ratio: f64,
    /// The date and time when the usage threshold was reached. The date and time must be in ISO 8601 format.
    #[serde(rename = "reached_at")]
    pub reached_at: String,
}

impl LifetimeUsageThresholdObject {
    pub fn new(amount_cents: i32, completion_ratio: f64, reached_at: String) -> LifetimeUsageThresholdObject {
        LifetimeUsageThresholdObject {
            amount_cents,
            completion_ratio,
            reached_at,
        }
    }
}

