/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MinimumCommitmentInput : Minimum commitment for this plan.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinimumCommitmentInput {
    /// The amount of the minimum commitment in cents.
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    /// Specifies the name that will be displayed on an invoice. If no value is set for this field, the default name will be used as the display name.
    #[serde(rename = "invoice_display_name", skip_serializing_if = "Option::is_none")]
    pub invoice_display_name: Option<String>,
    /// List of unique code used to identify the taxes.
    #[serde(rename = "tax_codes", skip_serializing_if = "Option::is_none")]
    pub tax_codes: Option<Vec<String>>,
}

impl MinimumCommitmentInput {
    /// Minimum commitment for this plan.
    pub fn new(amount_cents: i32) -> MinimumCommitmentInput {
        MinimumCommitmentInput {
            amount_cents,
            invoice_display_name: None,
            tax_codes: None,
        }
    }
}

