/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrrObject {
    /// Identifies the month to analyze MRR.
    #[serde(rename = "month")]
    pub month: String,
    /// The total amount of MRR, expressed in cents.
    #[serde(rename = "amount_cents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    /// The currency of MRR analytics. Format must be ISO 4217.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
}

impl MrrObject {
    pub fn new(month: String) -> MrrObject {
        MrrObject {
            month,
            amount_cents: None,
            currency: None,
        }
    }
}

