/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentRequestsPaginated {
    #[serde(rename = "payment_requests")]
    pub payment_requests: Vec<models::PaymentRequestObject>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl PaymentRequestsPaginated {
    pub fn new(payment_requests: Vec<models::PaymentRequestObject>, meta: models::PaginationMeta) -> PaymentRequestsPaginated {
        PaymentRequestsPaginated {
            payment_requests,
            meta: Box::new(meta),
        }
    }
}

