/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionsPaginated {
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<models::SubscriptionObject>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl SubscriptionsPaginated {
    pub fn new(subscriptions: Vec<models::SubscriptionObject>, meta: models::PaginationMeta) -> SubscriptionsPaginated {
        SubscriptionsPaginated {
            subscriptions,
            meta: Box::new(meta),
        }
    }
}

