/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletTransactionsPaginated {
    #[serde(rename = "wallet_transactions")]
    pub wallet_transactions: Vec<models::WalletTransactionObject>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
}

impl WalletTransactionsPaginated {
    pub fn new(wallet_transactions: Vec<models::WalletTransactionObject>, meta: models::PaginationMeta) -> WalletTransactionsPaginated {
        WalletTransactionsPaginated {
            wallet_transactions,
            meta: Box::new(meta),
        }
    }
}

