/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEndpointUpdateInput {
    #[serde(rename = "webhook_endpoint", skip_serializing_if = "Option::is_none")]
    pub webhook_endpoint: Option<Box<models::WebhookEndpointCreateInputWebhookEndpoint>>,
}

impl WebhookEndpointUpdateInput {
    pub fn new() -> WebhookEndpointUpdateInput {
        WebhookEndpointUpdateInput {
            webhook_endpoint: None,
        }
    }
}

